export const copy = {
  home: {
    headline: "I've done 150 brand deals. Let me show you how it actually works.",
    sub: "Creator, coach, and the guy brands call back. I help creators, actors, and business owners make content that gets seen and gets paid.",
    primaryCta: "Work with me",
    secondaryCta: "See the work",
    marqueeHeading: "Brands I've worked with",
    workHeading: "Some of the work",
    workLink: "See all the work",
    whoHeading: "Who I help",
    who: [
      {
        title: "Creators and actors",
        body: "You know how to be on camera. You don't know why some posts go and some don't, or how to get paid for it. That's the part I teach.",
        cta: "Coaching for creators",
        href: "/coaching",
      },
      {
        title: "Business owners and professionals",
        body: "Realtors, lawyers, dentists, trainers. You've been told to \"do social\" and you hate it. I'll give you a simple system you can keep up with.",
        cta: "Social for your business",
        href: "/coaching",
      },
      {
        title: "Brands and agencies",
        body: "You want a creator who understands your brief, your approvals, and your usage terms, and still makes something people watch. I've done it 150 times.",
        cta: "Hire me",
        href: "/brands",
      },
    ],
    howHeading: "How I work",
    how: [
      "I don't do slides. We open your page and work on it. You film, we watch it back, and I tell you what I'd change and why. Then you post it.",
      "Everything I teach comes from doing it: formats, hooks, how brands actually pick people, what a brief looks like, what to charge. Not theory.",
      "Before all this I spent ten years at PwC, where I was Director of Learning and Development on client programs, running training and change programs for large companies. I know how to make something stick for people who are busy and skeptical.",
    ],
    aboutTeaser:
      "I'm Peter. I make comedy with my family as The Sing Family, I'm a SAG-AFTRA actor, and I've negotiated more brand contracts than I'd like to count. I live in Orange County, CA.",
    aboutLink: "More about me",
    faqHeading: "Questions",
    ctaHeading: "Let's talk",
    ctaBody: "Email me, book a call, or DM me on any platform. I read everything and reply within two days.",
  },
  work: {
    title: "Work",
    heading: "The work",
    intro: "A few of the 150+ campaigns, with the numbers. Every one of these I wrote, shot, negotiated, and reported on.",
    repeatHeading: "Brands that came back",
    wallHeading: "All of them",
    tier1Heading: "The biggest names",
    ctaHeading: "Want this for your brand?",
    ctaBody: "I take on a small number of partnerships a year. Tell me what you're launching.",
    ctaButton: "For brands and agencies",
    viewPost: "See the post",
    watchMore: "Watch more",
    watchMoreUrl: "https://www.tiktok.com/@thesingfamily",
    play: "Play",
    openOn: "Open on",
    allChip: "All",
  },
  coaching: {
    title: "Coaching",
    heading: "Coaching",
    intro: "Three ways to work with me.",
    offers: [
      {
        key: "oneOnOne" as const,
        body: "You and me, on your page. We go through what you're posting, what's working, what isn't, and what to make next. If you're pitching brands or fielding offers, we go through pricing and the deal. Video call or in person in Orange County. Written recap after.",
        cta: "Book a call",
      },
      {
        key: "workshop" as const,
        body: "Small groups, in person in Orange County or online. We film in the room, watch it back, and fix it together. Every session stands alone.",
        cta: "Ask about workshops",
      },
      {
        key: "business" as const,
        body: "For professionals and small businesses who need to show up online without it taking over their life. We build a simple posting system around what you already do all day, then I review your first month.",
        cta: "Book a call",
      },
    ],
    closerBefore: "Not sure which one?",
    closerLink: "Email me",
    closerAfter: "and tell me what you're trying to do.",
    bookOption: "Book",
    introBefore: "Not sure yet?",
    introLink: "Book a free 15\u2011minute intro call.", // non-breaking hyphen so "15-minute" never wraps
    nextDateLabel: "Next date",
  },
  brands: {
    title: "Brands",
    heading: "For brands and agencies",
    intro: "I've been on the creator side of 150+ campaigns for 80+ brands. I know what a brief needs, what approvals look like, and what usage terms cost. I also know what people actually watch.",
    waysHeading: "Four ways to work together",
    ways: [
      {
        title: "Creator partnerships",
        body: "Sponsored content on The Sing Family, from concept to post-campaign report. Spark Ads and whitelisting available.",
      },
      {
        title: "Creative consulting",
        body: "Brief reviews, creator roster vetting, campaign teardowns. For agencies and in-house teams running creator programs.",
      },
      {
        title: "Speaking and panels",
        body: "Creator economy, brand partnerships, building an audience from zero.",
      },
      {
        title: "Team training",
        body: "Half-day or full-day sessions for marketing teams on working with creators. I ran this kind of training at PwC, where I was Director of Learning and Development on client programs.",
      },
    ],
    audienceHeading: "The audience",
    mediaKitButton: "Request the media kit",
    mediaKitSubject: "Media kit",
    ctaHeading: "Tell me what you're launching",
    ctaBody: "I reply within two days with a straight answer on fit, timing, and cost.",
  },
  about: {
    title: "About",
    heading: "About Peter",
    body: [
      "I'm Peter Sing. I run The Sing Family with my wife Elena, a comedy channel with about 2 million followers across TikTok, Instagram, and YouTube. Since 2019 we've done more than 150 paid campaigns for brands like Coca-Cola, Walmart, Amazon, McDonald's, Disney, Dove, Verizon, and Lexus. I write them, shoot them, negotiate them, and report on them.",
      "Before that I spent ten years at PwC, where I directed Learning and Development on client programs for Fortune 500 companies: training, change management, and internal communications for big system rollouts. Turns out that's most of coaching.",
      "I'm a SAG-AFTRA member and a trained actor, which is where the on-camera stuff comes from.",
      "I coach because I keep getting the same questions from creators, actors, and friends with businesses, and I'd rather answer them properly than badly in a DM.",
    ],
    timeline: [
      { when: "2014 to 2024", what: "PwC", detail: "Director of Learning and Development on client programs. Training, change management, and internal communications for Fortune 500 clients" },
      { when: "2019 to now", what: "The Sing Family", detail: "2M+ followers, 150+ brand deals" },
      { when: "Now", what: "Content Creator Coaching", detail: "1:1, workshops, and consulting for businesses" },
    ],
    education: "BA, Global Marketing and Finance, California State University, Fullerton. SAG-AFTRA member.",
    familyHeading: "The Sing Family",
  },
  contact: {
    title: "Contact",
    heading: "Say hi",
    body: "Tell me what you're working on and what's in the way. I reply within two days.",
    bookCall: "Book a call",
    copyEmail: "Copy",
    copied: "Copied",
    formHeading: "Or send a note",
    fields: {
      name: "Name",
      email: "Email",
      role: "I am a",
      message: "Message",
      submit: "Send",
    },
    roles: ["Creator or actor", "Business owner", "Brand or agency", "Press or event", "Other"],
    noForm: "The form is on its way. Email me in the meantime and I'll reply within two days.",
    handlesHeading: "Or DM me",
    dmLink: "@thesingfamily on Instagram",
    sending: "Sending",
    success: "Got it. I'll reply within two days.",
    errorBefore: "Something went wrong. Email me at",
    pickOne: "Pick one",
  },
  thanks: {
    title: "Thanks",
    heading: "Got it.",
    body: "I'll reply within two days.",
    back: "Back to the site",
  },
  privacy: {
    title: "Privacy",
    heading: "Privacy",
    updated: "Updated October 2026",
    body: [
      "This site is run by Peter Sing in Orange County, CA. Here is what it collects and what it does with it.",
      "Forms are handled by Formspree. If you fill in the contact form, Formspree sends me your name, email, what you do, and your message. I use it to reply to you. I don't add you to a list or share it with anyone.",
      "Bookings and payments are handled by Cal.com. When you book a session, Cal.com takes your details and Cal Pay processes the payment. I never see or store your card number. Their privacy policy covers what they collect.",
      "Analytics are handled by Vercel Web Analytics. It counts visits anonymously, sets no cookies, and doesn't identify you or follow you across other sites.",
      "If I turn on a Meta or TikTok pixel to measure ads, it can set a cookie in your browser. You can block it with your browser settings or an ad blocker and the site will still work.",
      "There is no newsletter, no account, and nothing stored about you beyond what's above.",
      "Questions, or want something deleted? Email contact@coachpetersing.com.",
    ],
  },
  nav: {
    cta: "Work with me",
    menu: "Menu",
  },
  footer: {
    tagline: "Content coaching from a creator with 150+ brand deals.",
    emailLabel: "Email",
    bookLabel: "Book a call",
    familyLabel: "The Sing Family",
    rights: "Peter Sing. All rights reserved.",
  },
  common: {
    bookCall: "Book a call",
    emailMe: "Email me",
    dm: "DM me",
  },
};
