export const copy = {
  home: {
    headline: "Content coaching for creators, actors, and small businesses.",
    sub: "I've been making videos with my family as The Sing Family since 2019, and along the way I've worked with brands like Coca-Cola, Walmart, Disney, and Dove. Now I help other people get better at it, one on one.",
    primaryCta: "Work with me",
    secondaryCta: "See the work",
    marqueeHeading: "Brands I've worked with",
    workHeading: "Brand partnerships",
    workLink: "See more campaigns",
    whoHeading: "Who I help",
    who: [
      {
        title: "Creators and actors",
        body: "You're comfortable on camera but want your posts to land more consistently, or you're starting to get brand interest and want help with it.",
        cta: "Coaching for creators",
        href: "/coaching",
      },
      {
        title: "Business owners and professionals",
        body: "You know you should be posting, but it's hard to know what to make or how to keep it going. We'll find something simple that fits your week.",
        cta: "Social for your business",
        href: "/coaching",
      },
      {
        title: "Brands and agencies",
        body: "I also work with brands on creator campaigns, from the brief through the finished post.",
        cta: "Working with brands",
        href: "/brands",
      },
    ],
    howHeading: "How I work",
    how: [
      "Sessions are mostly hands-on. We look at your account together, talk through what's working and what isn't, and figure out what to try next.",
      "A lot of what I share comes from my own trial and error over the last seven years, including plenty of brand campaigns that taught me what audiences respond to.",
      "I also spent ten years at PwC as Director of Learning and Development on client programs with budgets up to $100M+, running training for teams at large companies.",
    ],
    aboutTeaser:
      "I'm Peter. I live in Orange County with my wife Elena and our kids, and we make comedy videos together as The Sing Family. I'm also a SAG-AFTRA actor.",
    aboutLink: "More about me",
    faqHeading: "Questions",
    ctaHeading: "Want to talk?",
    ctaBody: "Book a session or send me a note. I'll get back to you within two days.",
  },
  work: {
    title: "Work",
    heading: "The work",
    intro: "A selection of brand campaigns from the last few years.",
    repeatHeading: "Repeat partners",
    wallHeading: "All brands",
    tier1Heading: "A few you may know",
    ctaHeading: "Working on a campaign?",
    ctaBody: "I take on a small number of brand partnerships each year. Tell me what you have in mind.",
    ctaButton: "For brands and agencies",
    viewPost: "See the post",
    watchMore: "Watch more",
    watchMoreUrl: "https://www.tiktok.com/@thesingfamily",
    play: "Play",
    openOn: "Open on",
    allChip: "All",
  },
  coaching: {
    title: "Coaching",
    heading: "Coaching",
    intro: "Three ways to work with me.",
    offers: [
      {
        key: "oneOnOne" as const,
        body: "We sit down with your account and go through what you've been posting and what you might try next. If you're starting to talk with brands, we can go over pricing and the deal too. Sessions are over video or in person in Orange County, and I send a short written recap afterward.",
        cta: "Book a session",
      },
      {
        key: "workshop" as const,
        body: "These are small group sessions, in person in Orange County or online. We film short clips together and then watch them back as a group to see what could be better. Each session stands on its own, so you can come to just one.",
        cta: "Ask about workshops",
      },
      {
        key: "business" as const,
        body: "This is for professionals and small business owners who want to post regularly without it taking over their week. We put together a simple plan built around the work you already do, and I look over your first month of posts with you.",
        cta: "Book a session",
      },
    ],
    closerBefore: "Not sure which one?",
    closerLink: "Email me",
    closerAfter: "and tell me what you're trying to do.",
    bookOption: "Book",
    nextDateLabel: "Next date",
  },
  brands: {
    title: "Brands",
    heading: "For brands and agencies",
    intro: "I've worked on the creator side of campaigns for brands like Coca-Cola, Walmart, Amazon, and Dove since 2019. I'm happy to help with partnerships, briefs, or training your team on working with creators.",
    waysHeading: "Four ways to work together",
    ways: [
      {
        title: "Creator partnerships",
        body: "Sponsored videos on The Sing Family, from the first concept through the post-campaign report. Spark Ads and whitelisting are available too.",
      },
      {
        title: "Creative consulting",
        body: "For agencies and in-house teams running creator programs, I can look over a brief or a creator list, or go back through a past campaign with you.",
      },
      {
        title: "Speaking and panels",
        body: "I'm glad to join panels or speak at events about brand partnerships and growing an audience.",
      },
      {
        title: "Team training",
        body: "I run half-day or full-day sessions for marketing teams on working with creators. I did this kind of training at PwC, where I was Director of Learning and Development on client programs with budgets up to $100M+.",
      },
    ],
    audienceHeading: "The audience",
    mediaKitButton: "Request the media kit",
    mediaKitSubject: "Media kit",
    ctaHeading: "Tell me what you're working on",
    ctaBody: "I'll get back to you within two days and let you know if I'm a good fit.",
  },
  about: {
    title: "About",
    heading: "About Peter",
    body: [
      "I'm Peter Sing. My wife Elena and I started making comedy videos as The Sing Family in 2019, and about 1.7 million people now follow along on TikTok, Instagram, and YouTube. Over the years we've partnered with brands like Coca-Cola, Walmart, Amazon, McDonald's, Disney, Dove, Verizon, and Lexus. I handle most of the work on those campaigns myself, from writing and shooting to the contract and the report at the end.",
      "I also spent ten years at PwC, from 2014 to 2024, as Director of Learning and Development on client programs with budgets up to $100M+. Most of that work was helping teams at large companies learn new systems when their organizations rolled them out.",
      "I'm a SAG-AFTRA member and have trained as an actor, which helps a lot with the on-camera side.",
      "I started coaching because friends and other creators kept asking me the same questions, and I wanted to give them better answers than I could in a quick DM.",
    ],
    timeline: [
      { when: "2014 to 2024", what: "PwC", detail: "Director of Learning and Development on client programs with budgets up to $100M+" },
      { when: "2019 to now", what: "The Sing Family", detail: "Comedy videos with my family" },
      { when: "Now", what: "Content Creator Coaching", detail: "Coaching for creators and small businesses" },
    ],
    familyHeading: "The Sing Family",
  },
  contact: {
    title: "Contact",
    heading: "Say hi",
    body: "Tell me a little about what you're working on. I'll get back to you within two days.",
    bookCall: "Book a session",
    copyEmail: "Copy",
    copied: "Copied",
    formHeading: "Or send a note",
    fields: {
      name: "Name",
      email: "Email",
      role: "I am a",
      message: "Message",
      submit: "Send",
    },
    roles: ["Creator or actor", "Business owner", "Brand or agency", "Press or event", "Other"],
    noForm: "The form is on its way. Email me in the meantime and I'll get back to you within two days.",
    handlesHeading: "Or DM me",
    dmLink: "@thesingfamily on Instagram",
    sending: "Sending",
    success: "Thanks, I got your note. I'll get back to you within two days.",
    errorBefore: "Something went wrong. Email me at",
    pickOne: "Pick one",
  },
  thanks: {
    title: "Thanks",
    heading: "Thanks for reaching out.",
    body: "I'll get back to you within two days.",
    back: "Back to the site",
  },
  privacy: {
    title: "Privacy",
    heading: "Privacy",
    updated: "Updated October 2026",
    body: [
      "This site is run by Peter Sing in Orange County, CA. Here is what it collects and what it does with it.",
      "Forms are handled by Formspree. If you fill in the contact form, Formspree sends me your name, email, what you do, and your message. I use it to reply to you. I don't add you to a list or share it with anyone.",
      "Bookings and payments are handled by Cal.com. When you book a session, Cal.com takes your details and Cal Pay processes the payment. I never see or store your card number. Their privacy policy covers what they collect.",
      "Analytics are handled by Vercel Web Analytics. It counts visits anonymously, sets no cookies, and doesn't identify you or follow you across other sites.",
      "If I turn on a Meta or TikTok pixel to measure ads, it can set a cookie in your browser. You can block it with your browser settings or an ad blocker and the site will still work.",
      "There is no newsletter, no account, and nothing stored about you beyond what's above.",
      "Questions, or want something deleted? Email contact@coachpetersing.com.",
    ],
  },
  nav: {
    cta: "Work with me",
    menu: "Menu",
  },
  footer: {
    tagline: "Content coaching for creators, actors, and small businesses.",
    emailLabel: "Email",
    bookLabel: "Book a session",
    familyLabel: "The Sing Family",
    rights: "Peter Sing. All rights reserved.",
  },
  // Free 15-minute consult, requested by email. Non-breaking hyphen so "15-minute" never wraps.
  consult: {
    subject: "Free consult request",
    coachingBefore: "Not sure yet? Email me at",
    coachingAfter: "to request a free 15\u2011minute consult.",
    shortBefore: "Want to talk first? Email",
    shortAfter: "for a free 15\u2011minute consult.",
  },
  common: {
    bookCall: "Book a session",
    emailMe: "Email me",
    dm: "DM me",
  },
};
